language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-chill' ]; then cd .. && eval "mv $currentfolder generator-chill" && cd generator-chill; fi

